name: Generate SBOM and Publish

on:
  push:
  pull_request:

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment (Node.js 18 o superior)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      #- name: Install dependencies
       # run: npm install

# Install cdxgen globally
      - name: Install cdxgen
        run: npm install @cyclonedx/cdxgen

      - name: Generate SBOM
        run: npx cdxgen 

              # Generate SBOM
      - name: Generate SBOM
        run: cdxgen -t npm .

              # Generate SBOM
      - name: Generate SBOM
        run: cdxgen -t npm . -o sbom.json
        
      # Upload SBOM as an artifact
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json
